#!/usr/bin/perl
#
# Magic markers:
#%# family=auto
#%# capabilities=autoconf

$sock       = '/var/run/php5-fpm.sock';
$exports    = 'export SCRIPT_NAME=/status && export SCRIPT_FILENAME=/status && export REQUEST_METHOD=GET';
$response   = `$exports && /usr/bin/cgi-fcgi -bind -connect $sock`;

if ( defined $ARGV[0] and $ARGV[0] eq "autoconf" )
{
	if ($response =~ /accepted conn:\s+([0-9\.]+)/im) {
		print "yes\n";
		exit 1;
	} else {
		print "no\n";
		exit 0;
	}
}


if ( defined $ARGV[0] and $ARGV[0] eq "config" )
{
	print('graph_title PHP5-FPM Status
graph_args --base 1024 -l 0
graph_vlabel Connections
graph_category PHP
graph_order active idle total
graph_info Plugin created by TJ Stein
active.label Active
active.draw AREA
idle.label Idle
idle.draw STACK
total.label Total
total.draw LINE1
');

	exit 0;
}


if ($response =~ /idle processes:\s+([0-9\.]+)/im) {
    print "idle.value $1\n";
} else {
    print "idle.value U\n";
}
if ($response =~ /active processes:\s+([0-9\.]+)/im) {
    print "active.value $1\n";
} else {
    print "active.value U\n";
}
if ($response =~ /total processes:\s+([0-9\.]+)/im) {
    print "total.value $1\n";
} else {
    print "total.value U\n";
}
