#!/usr/bin/perl
#
# Magic markers:
#%# family=auto
#%# capabilities=autoconf

$sock       = '/var/run/php5-fpm.sock';
$exports    = 'export SCRIPT_NAME=/status && export SCRIPT_FILENAME=/status && export REQUEST_METHOD=GET';
$response   = `$exports && /usr/bin/cgi-fcgi -bind -connect $sock`;


if ( defined $ARGV[0] and $ARGV[0] eq "autoconf" )
{
	if ($response =~ /accepted conn:\s+([0-9\.]+)/im) {
		print "yes\n";
		exit 1;
	} else {
		print "no\n";
		exit 0;
	}
}

if ( defined $ARGV[0] and $ARGV[0] eq "config" )
{
	print('graph_title PHP5-FPM Accepted Connections
graph_args --base 1024 -l 0
graph_vlabel Connections
graph_category PHP
graph_info Plugin created by TJ Stein
accepted.label Accepted
accepted.draw AREA
accepted.type DERIVE
accepted.min 0
');

	exit 0;
}

if ($response =~ /accepted conn:\s+([0-9\.]+)/im) {
	print "accepted.value $1\n";
} else {
	print "accepted.value U\n";
}
